"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  parseDiff,
  tokenize,
  markEdits,
  Diff,
  Hunk,
  Decoration,
  getChangeKey,
  computeNewLineNumber,
  computeOldLineNumber,
  isDelete,
  type FileData,
  type ChangeData,
  type ChangeEventArgs,
  type HunkData,
  type GutterOptions,
} from "react-diff-view";
import "react-diff-view/style/index.css";
import { refractor } from "refractor";
import {
  Columns2,
  Rows2,
  ExternalLink,
  GitCompare,
  FileWarning,
  ChevronRight,
  AlertTriangle,
  ArrowLeft,
  PanelLeftClose,
  PanelLeftOpen,
  Clock,
  List,
  Target,
  MessageSquarePlus,
  Trash2,
} from "lucide-react";
import { FileTree } from "@/components/file-tree/file-tree";
import { currentTabWs } from "@/lib/tab-ws";
import { isWhitespaceOnlyHunk } from "@/lib/diff-shared";
import type { FileStatus, FileLeafInput } from "@/lib/file-tree";
import type { ChangedFile, FileDiff } from "@/lib/diff-shared";
import type { DiffComment } from "@/lib/diff-comments";
import { cn } from "@/lib/utils";

// The drill layer: changed-files tree (left, collapsible + drag-resizable) → git diff of the
// selected file (right). Reached from the Mission Control overview; Back returns there. Word-level
// edit emphasis via markEdits; whitespace-only hunks fold to a one-line row (skim-budget noise).
// When the active plan has a scope contract, the tree groups edits On-plan vs Strayed vs Other.

type ViewType = "split" | "unified";
type GroupTone = "plan" | "warn" | "muted";

const SIDEBAR_OPEN_KEY = "beacon:changes-sidebar-open";
const SIDEBAR_W_KEY = "beacon:changes-sidebar-w";
const SIDEBAR_MIN = 220;
const SIDEBAR_MAX = 620;

// react-diff-view's tokenize expects refractor.highlight() to return an ARRAY of hast nodes (its
// v3 API); refractor v5 returns a Root, so unwrap to .children.
const refractorAdapter = {
  highlight: (value: string, lang: string) => refractor.highlight(value, lang).children,
};

// Prism token palette (dark) for the tokenized diff. Injected as a runtime <style> because
// Tailwind/Turbopack strips hand-written `.token.*` rules from globals.css (the classes are
// generated by refractor at runtime, so the build's purge drops them).
const PRISM_CSS = `
.beacon-diff .token.comment,.beacon-diff .token.prolog,.beacon-diff .token.doctype,.beacon-diff .token.cdata{color:#6b7684;font-style:italic}
.beacon-diff .token.punctuation{color:#9aa4b2}
.beacon-diff .token.keyword,.beacon-diff .token.atrule,.beacon-diff .token.important,.beacon-diff .token.rule{color:#c792ea}
.beacon-diff .token.string,.beacon-diff .token.char,.beacon-diff .token.attr-value,.beacon-diff .token.regex{color:#a5d6a7}
.beacon-diff .token.number,.beacon-diff .token.boolean,.beacon-diff .token.constant,.beacon-diff .token.symbol{color:#f78c6c}
.beacon-diff .token.function,.beacon-diff .token.class-name,.beacon-diff .token.maybe-class-name{color:#82aaff}
.beacon-diff .token.tag,.beacon-diff .token.property,.beacon-diff .token.selector,.beacon-diff .token.attr-name,.beacon-diff .token.builtin{color:#ffcb6b}
.beacon-diff .token.operator,.beacon-diff .token.entity,.beacon-diff .token.url{color:#89ddff}
.beacon-diff .token.variable{color:#f07178}
`;

function toTreeStatus(s: ChangedFile["status"]): FileStatus {
  return s === "added" ? "added" : s === "deleted" ? "deleted" : "modified";
}
function toTree(files: ChangedFile[]): FileLeafInput[] {
  return files.map((f) => ({ path: f.path, status: toTreeStatus(f.status), meta: `+${f.additions} −${f.deletions}` }));
}
export function openInEditor(path: string) {
  fetch(`/api/open?path=${encodeURIComponent(path)}`).catch(() => {});
}

// A hunk whose every changed line is whitespace-only reflow — folded by default.
function hunkIsFormattingOnly(h: HunkData): boolean {
  const removed = h.changes.filter((c) => c.type === "delete").map((c) => c.content);
  const added = h.changes.filter((c) => c.type === "insert").map((c) => c.content);
  return (removed.length > 0 || added.length > 0) && isWhitespaceOnlyHunk(removed, added);
}

export function DiffDetail({
  repo,
  files,
  touched,
  contract,
  initialPath,
  onBack,
}: {
  repo: boolean;
  files: ChangedFile[];
  touched: string[];
  contract?: { declaredFiles: string[]; authorizedExtras: string[] } | null;
  initialPath: string | null;
  onBack: () => void;
}) {
  const sessionSet = useMemo(() => new Set(touched), [touched]);
  const inSession = (f: ChangedFile) => sessionSet.has(f.path) || (!!f.oldPath && sessionSet.has(f.oldPath));

  // The active plan's file set (declaredFiles ∪ authorizedExtras). Scoping only kicks in when the
  // contract actually names files — an empty contract falls back to the session view below.
  const onPlanSet = useMemo(
    () => (contract ? new Set([...contract.declaredFiles, ...contract.authorizedExtras]) : null),
    [contract],
  );
  const hasScope = !!onPlanSet && onPlanSet.size > 0;
  const inPlan = (f: ChangedFile) => !!onPlanSet && (onPlanSet.has(f.path) || (!!f.oldPath && onPlanSet.has(f.oldPath)));

  const [mode, setMode] = useState<ViewType>("split");
  const [selected, setSelected] = useState<string | null>(initialPath);

  // ── Collapsible + resizable file-list sidebar ────────────────────────────────
  const [sidebarOpen, setSidebarOpen] = useState<boolean>(() => {
    if (typeof window === "undefined") return true;
    try {
      return window.localStorage.getItem(SIDEBAR_OPEN_KEY) !== "0";
    } catch {
      return true;
    }
  });
  const [sidebarW, setSidebarW] = useState<number>(() => {
    if (typeof window === "undefined") return 320;
    try {
      const v = Number(window.localStorage.getItem(SIDEBAR_W_KEY));
      return v ? Math.max(SIDEBAR_MIN, Math.min(SIDEBAR_MAX, v)) : 320;
    } catch {
      return 320;
    }
  });
  const toggleSidebar = useCallback(() => {
    setSidebarOpen((o) => {
      const next = !o;
      try {
        localStorage.setItem(SIDEBAR_OPEN_KEY, next ? "1" : "0");
      } catch {
        /* ignore */
      }
      return next;
    });
  }, []);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const draggingRef = useRef(false);
  const onResizeDown = useCallback((e: React.PointerEvent) => {
    e.preventDefault();
    draggingRef.current = true;
    document.body.style.cursor = "col-resize";
    document.body.style.userSelect = "none";
  }, []);
  useEffect(() => {
    const onMove = (e: PointerEvent) => {
      if (!draggingRef.current || !containerRef.current) return;
      const left = containerRef.current.getBoundingClientRect().left;
      setSidebarW(Math.max(SIDEBAR_MIN, Math.min(SIDEBAR_MAX, e.clientX - left)));
    };
    const onUp = () => {
      if (!draggingRef.current) return;
      draggingRef.current = false;
      document.body.style.cursor = "";
      document.body.style.userSelect = "";
      try {
        localStorage.setItem(SIDEBAR_W_KEY, String(sidebarW));
      } catch {
        /* ignore */
      }
    };
    window.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onUp);
    return () => {
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onUp);
    };
  }, [sidebarW]);

  // Contract mode: partition changes into On-plan, Strayed (off-plan but edited THIS session — the
  // divergence signal), and Other (pre-existing uncommitted noise).
  const groups = useMemo(() => {
    if (!hasScope) return null;
    return {
      onPlan: files.filter(inPlan),
      strayed: files.filter((f) => !inPlan(f) && inSession(f)),
      other: files.filter((f) => !inPlan(f) && !inSession(f)),
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [files, hasScope, onPlanSet, sessionSet]);

  // Session-mode scope pill (only when there's no contract to scope by).
  const hasSession = files.some(inSession);
  const [scope, setScope] = useState<"session" | "all">("session");
  const effScope = scope === "session" && !hasSession ? "all" : scope;

  // Flat ordered list for selection default + lookup.
  const visibleList = useMemo(() => {
    if (groups) return [...groups.onPlan, ...groups.strayed, ...groups.other];
    return effScope === "all" ? files : files.filter(inSession);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [groups, files, effScope, sessionSet]);

  const byPath = useMemo(() => new Map(files.map((f) => [f.path, f])), [files]);
  const activePath = selected && visibleList.some((f) => f.path === selected) ? selected : visibleList[0]?.path ?? null;
  const active = activePath ? byPath.get(activePath) ?? null : null;
  const activeStrayed = !!active && !!groups && groups.strayed.some((f) => f.path === active.path);

  // Lazily fetch the selected file's raw diff. Re-fetches on selection change OR when the file list
  // changes (live refresh). Readiness derives from `raw.path === active.path` (no sync setState).
  const [raw, setRaw] = useState<{ path: string; diff: string } | null>(null);
  useEffect(() => {
    if (!active || active.binary || active.tooLarge) return;
    const path = active.path;
    const old = active.oldPath ?? "";
    let ignore = false;
    const ws = currentTabWs();
    fetch(`/api/changes?path=${encodeURIComponent(path)}&old=${encodeURIComponent(old)}`, {
      cache: "no-store",
      headers: ws ? { "x-beacon-workspace": ws } : undefined,
    })
      .then((r) => r.json() as Promise<FileDiff>)
      .then((c) => {
        if (!ignore) setRaw({ path, diff: c.diff ?? "" });
      })
      .catch(() => {});
    return () => {
      ignore = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activePath, active?.binary, active?.tooLarge, files]);

  const parsed: FileData | null = useMemo(() => {
    if (!raw?.diff) return null;
    try {
      // A rename git renders as delete+add (below its similarity threshold) yields two blocks —
      // pick the one for the file we fetched, not blindly [0].
      const fs = parseDiff(raw.diff);
      return fs.find((f) => f.newPath === raw.path) ?? fs[0] ?? null;
    } catch {
      return null;
    }
  }, [raw]);

  // Syntax-highlight the diff via refractor (Prism) + word-level edit emphasis (markEdits).
  // Unknown languages fall back to a plain diff.
  const tokens = useMemo(() => {
    if (!parsed || !active) return undefined;
    try {
      const highlight = refractor.registered(active.lang);
      return tokenize(parsed.hunks, {
        highlight,
        refractor: refractorAdapter,
        language: active.lang,
        enhancers: [markEdits(parsed.hunks, { type: "block" })],
      });
    } catch {
      return undefined;
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [parsed, active?.lang]);
  const diffReady = raw && active && raw.path === active.path;

  // Whitespace-only hunks the user explicitly expanded (reset per file).
  const [showFormatting, setShowFormatting] = useState<Set<string>>(new Set());
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setShowFormatting(new Set());
  }, [activePath]);

  // ── Line-comments on the diff → the running agent ────────────────────────────
  // Hover a gutter → "+" → comment; it's stored per file+line WITH the line's content, and the
  // PreToolUse guard hook injects it as non-blocking context at the agent's next edit. The diff
  // shifts constantly under a working agent, so comments RE-ANCHOR by content each refresh; a
  // comment whose line no longer exists renders in the orphan strip ("the agent changed this").
  const [fileComments, setFileComments] = useState<DiffComment[]>([]);
  const [composer, setComposer] = useState<{ key: string; line: number; side: "old" | "new"; text: string } | null>(null);
  const [draft, setDraft] = useState("");
  const [holdDraft, setHoldDraft] = useState(false);
  const reloadComments = useCallback(async (path: string) => {
    const ws = currentTabWs();
    const r = (await fetch(`/api/changes/comment?file=${encodeURIComponent(path)}`, {
      cache: "no-store",
      headers: ws ? { "x-beacon-workspace": ws } : undefined,
    })
      .then((res) => res.json())
      .catch(() => null)) as { comments?: DiffComment[] } | null;
    setFileComments(r?.comments ?? []);
  }, []);
  useEffect(() => {
    // Deliberate reset-on-selection-change: a new file gets a clean composer + its own comments.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setComposer(null);
    setDraft("");
    if (activePath) void reloadComments(activePath);
    else setFileComments([]);
  }, [activePath, reloadComments]);

  const addComment = useCallback(async () => {
    if (!composer || !active || !draft.trim()) return;
    const ws = currentTabWs();
    await fetch("/api/changes/comment", {
      method: "POST",
      headers: { "content-type": "application/json", ...(ws ? { "x-beacon-workspace": ws } : {}) },
      body: JSON.stringify({
        file: active.path,
        line: composer.line,
        side: composer.side,
        body: draft.trim(),
        text: composer.text,
        held: holdDraft || undefined,
      }),
    }).catch(() => {});
    setComposer(null);
    setDraft("");
    setHoldDraft(false);
    void reloadComments(active.path);
  }, [composer, active, draft, holdDraft, reloadComments]);

  // Toggle one comment's hold / release the whole held batch.
  const patchComment = useCallback(
    async (body: { id?: string; held?: boolean; release?: boolean }) => {
      const ws = currentTabWs();
      await fetch("/api/changes/comment", {
        method: "PATCH",
        headers: { "content-type": "application/json", ...(ws ? { "x-beacon-workspace": ws } : {}) },
        body: JSON.stringify(body),
      }).catch(() => {});
      if (active) void reloadComments(active.path);
    },
    [active, reloadComments],
  );

  const deleteComment = useCallback(
    async (id: string) => {
      const ws = currentTabWs();
      await fetch(`/api/changes/comment?id=${encodeURIComponent(id)}`, {
        method: "DELETE",
        headers: ws ? { "x-beacon-workspace": ws } : undefined,
      }).catch(() => {});
      if (active) void reloadComments(active.path);
    },
    [active, reloadComments],
  );

  // Index the CURRENT diff two ways: "side:line" → changeKey (composer placement) and
  // side → trimmed content → [{key,line}] (content re-anchoring of stored comments).
  const diffIndex = useMemo(() => {
    const byLine = new Map<string, string>();
    const byContent = { old: new Map<string, { key: string; line: number }[]>(), new: new Map<string, { key: string; line: number }[]>() };
    if (!parsed) return { byLine, byContent };
    const push = (side: "old" | "new", t: string, key: string, line: number) => {
      if (!t) return;
      const arr = byContent[side].get(t);
      if (arr) arr.push({ key, line });
      else byContent[side].set(t, [{ key, line }]);
    };
    for (const h of parsed.hunks)
      for (const ch of h.changes) {
        const key = getChangeKey(ch);
        const t = ch.content.trim();
        const nl = computeNewLineNumber(ch);
        if (nl && nl > 0) {
          byLine.set(`new:${nl}`, key);
          push("new", t, key, nl);
        }
        const ol = computeOldLineNumber(ch);
        if (ol && ol > 0) {
          byLine.set(`old:${ol}`, key);
          push("old", t, key, ol);
        }
      }
    return { byLine, byContent };
  }, [parsed]);

  const openComposer = useCallback((ch: ChangeData, sideHint?: "old" | "new") => {
    const side: "old" | "new" = sideHint === "old" || (sideHint === undefined && isDelete(ch)) ? "old" : "new";
    const line = side === "old" ? computeOldLineNumber(ch) : computeNewLineNumber(ch);
    if (!line || line <= 0) return;
    setComposer({ key: getChangeKey(ch), line, side, text: ch.content.trim() });
    setDraft("");
  }, []);

  const gutterEvents = useMemo(
    () => ({
      onClick: (args: ChangeEventArgs) => {
        const ch = args.change as ChangeData | null;
        if (ch) openComposer(ch, args.side);
      },
    }),
    [openComposer],
  );

  // Hover a gutter → the "+" affordance (GitHub muscle memory) instead of an invisible click zone.
  const renderGutter = useCallback(
    ({ change, side, inHoverState, renderDefault }: GutterOptions) => {
      if (inHoverState && change) {
        return (
          <button
            type="button"
            title="Comment on this line — the agent gets it at its next edit"
            className="flex w-full items-center justify-center rounded-sm bg-[#ff7a45] text-[13px] font-bold leading-none text-white"
            onClick={(e) => {
              e.stopPropagation();
              openComposer(change, side);
            }}
          >
            +
          </button>
        );
      }
      return renderDefault();
    },
    [openComposer],
  );

  // Place each stored comment: 1. exact content match on its side (nearest to the stored line —
  // the agent shifting code moves the comment WITH the line), 2. legacy line match, 3. orphaned
  // (the agent changed/removed that line — surfaced in the strip above the diff, never dropped).
  const { widgets, orphans } = useMemo(() => {
    const byKey = new Map<string, { comments: DiffComment[]; composer: boolean }>();
    const orphaned: DiffComment[] = [];
    const at = (k: string) => {
      let v = byKey.get(k);
      if (!v) {
        v = { comments: [], composer: false };
        byKey.set(k, v);
      }
      return v;
    };
    for (const c of fileComments) {
      const candidates = c.text ? diffIndex.byContent[c.side].get(c.text) : undefined;
      if (candidates?.length) {
        const best = candidates.reduce((a, b) => (Math.abs(a.line - c.line) <= Math.abs(b.line - c.line) ? a : b));
        at(best.key).comments.push(c);
      } else {
        const k = diffIndex.byLine.get(`${c.side}:${c.line}`);
        // Line-only fallback ONLY for legacy comments with no stored text — with text stored, a
        // missing content match means the line truly changed.
        if (!c.text && k) at(k).comments.push(c);
        else orphaned.push(c);
      }
    }
    if (composer) at(composer.key).composer = true;
    const w: Record<string, React.ReactNode> = {};
    for (const [k, v] of byKey) {
      w[k] = (
        <div className="border-y border-[#ff7a45]/20 bg-[#ff7a45]/[0.04] px-3 py-2">
          {v.comments.map((c) => (
            <CommentCard
              key={c.id}
              c={c}
              onDelete={() => void deleteComment(c.id)}
              onToggleHeld={(held) => void patchComment({ id: c.id, held })}
            />
          ))}
          {v.composer && (
            <ComposerBox
              value={draft}
              onChange={setDraft}
              hold={holdDraft}
              onHold={setHoldDraft}
              onSubmit={() => void addComment()}
              onCancel={() => {
                setComposer(null);
                setDraft("");
              }}
            />
          )}
        </div>
      );
    }
    return { widgets: w, orphans: orphaned };
  }, [fileComments, diffIndex, composer, draft, holdDraft, addComment, deleteComment, patchComment]);

  const heldCount = fileComments.filter((c) => c.held && !c.deliveredAt).length;

  // Below this sidebar width the header would wrap, so labels collapse to icons (title hides,
  // scope pill + plan badge become icon-only with the text moved to tooltips).
  const narrow = sidebarW < 300;
  const SCOPE_META = {
    session: { label: "This session", Icon: Clock, title: "Files edited this session" },
    all: { label: "All", Icon: List, title: "All uncommitted changes" },
  } as const;
  const scopePill = (
    <div className="ml-auto flex items-center gap-0.5 rounded-full border border-white/10 p-0.5">
      {(["session", "all"] as const).map((s) => {
        const { label, Icon, title } = SCOPE_META[s];
        const disabled = s === "session" && !hasSession;
        return (
          <button
            key={s}
            type="button"
            onClick={() => setScope(s)}
            disabled={disabled}
            className={cn(
              "flex items-center justify-center rounded-full text-[10px] font-medium transition-colors",
              narrow ? "size-5" : "px-2 py-0.5",
              effScope === s ? "bg-white/10 text-foreground" : "text-muted-foreground hover:text-foreground",
              disabled && "opacity-40",
            )}
            title={title}
          >
            {narrow ? <Icon className="size-3" /> : label}
          </button>
        );
      })}
    </div>
  );

  return (
    <div ref={containerRef} className="flex min-h-0 flex-1">
      <style>{PRISM_CSS}</style>
      {/* LEFT — changed-files tree (collapsible + drag-resizable) */}
      {sidebarOpen ? (
        <aside style={{ width: sidebarW }} className="flex min-w-0 shrink-0 flex-col border-r border-white/10 bg-background">
          <div className="flex items-center gap-2 px-3 pb-2 pt-3">
            <button
              type="button"
              onClick={onBack}
              title="Back to overview"
              className="flex size-5 shrink-0 items-center justify-center rounded text-muted-foreground/70 transition-colors hover:bg-white/[0.06] hover:text-foreground"
            >
              <ArrowLeft className="size-3.5" />
            </button>
            <button
              type="button"
              onClick={toggleSidebar}
              title="Hide the file list"
              className="flex size-5 shrink-0 items-center justify-center rounded text-muted-foreground/70 transition-colors hover:bg-white/[0.06] hover:text-foreground"
            >
              <PanelLeftClose className="size-3.5" />
            </button>
            <GitCompare className="size-4 shrink-0 text-[#ff7a45]" />
            {!narrow && <h1 className="text-sm font-semibold tracking-tight">Changes</h1>}
            <span className="text-[11px] tabular-nums text-muted-foreground">{visibleList.length}</span>
            {hasScope ? (
              <span
                className={cn(
                  "ml-auto flex items-center rounded-full border border-emerald-400/25 bg-emerald-400/10 font-medium text-emerald-300/90",
                  narrow ? "size-5 justify-center" : "gap-1 px-2 py-0.5 text-[10px]",
                )}
                title={`Scoped to this plan — ${onPlanSet!.size} file${onPlanSet!.size === 1 ? "" : "s"} in scope`}
              >
                {narrow ? <Target className="size-3" /> : "Plan-scoped"}
              </span>
            ) : repo && files.length > 0 ? (
              scopePill
            ) : null}
          </div>
          <div className="min-h-0 flex-1 overflow-y-auto px-1.5 pb-4">
            {!repo ? (
              <p className="px-2 py-4 text-[11px] text-muted-foreground">Not a git repository.</p>
            ) : files.length === 0 ? (
              <p className="px-2 py-4 text-[11px] leading-relaxed text-muted-foreground">
                No uncommitted changes yet — edits the agent makes as it executes the plan show up
                here live.
              </p>
            ) : groups ? (
              <>
                <TreeGroup label="On plan" tone="plan" files={groups.onPlan} onSelect={setSelected} emptyNote="No plan files changed yet." />
                {groups.strayed.length > 0 ? (
                  <TreeGroup label="Strayed" tone="warn" files={groups.strayed} onSelect={setSelected} />
                ) : groups.onPlan.length > 0 ? (
                  <p className="mb-1 px-2 py-1 text-[10px] text-emerald-400/70">✓ No strays — all session edits are on-plan.</p>
                ) : null}
                {groups.other.length > 0 && (
                  <TreeGroup label="Other uncommitted" tone="muted" files={groups.other} onSelect={setSelected} defaultOpen={false} />
                )}
              </>
            ) : (
              <FileTree files={toTree(visibleList)} onSelect={setSelected} />
            )}
          </div>
        </aside>
      ) : null}
      {sidebarOpen ? (
        // Drag-to-resize handle (a thin bar with a wide invisible hit area), same as /plan's split.
        <div
          onPointerDown={onResizeDown}
          className="group relative w-px shrink-0 cursor-col-resize bg-white/10 hover:bg-white/20"
          title="Drag to resize"
        >
          <div className="absolute inset-y-0 -left-1.5 right-[-6px] z-10" />
        </div>
      ) : (
        // Collapsed rail — a slim reopen affordance so the file list is one click away.
        <aside className="flex w-10 shrink-0 flex-col items-center gap-1 border-r border-white/10 bg-background py-2">
          <button
            type="button"
            onClick={onBack}
            title="Back to overview"
            className="flex size-7 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-white/[0.06] hover:text-foreground"
          >
            <ArrowLeft className="size-4" />
          </button>
          <button
            type="button"
            onClick={toggleSidebar}
            title={`Show the file list · ${visibleList.length}`}
            className="flex size-7 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-white/[0.06] hover:text-foreground"
          >
            <PanelLeftOpen className="size-4" />
          </button>
        </aside>
      )}

      {/* RIGHT — diff of the selected file */}
      <main className="flex min-w-0 flex-1 flex-col bg-background">
        {active ? (
          <>
            <div className="flex items-center gap-2 border-b border-white/10 px-4 py-2">
              {activeStrayed && (
                <span
                  className="flex shrink-0 items-center gap-1 rounded-full border border-amber-400/30 bg-amber-400/10 px-1.5 py-0.5 text-[10px] font-medium text-amber-300"
                  title="This file is outside the plan's declared scope"
                >
                  <AlertTriangle className="size-3" /> Strayed
                </span>
              )}
              <span className="truncate font-mono text-[12px] text-foreground/90" title={active.path}>
                {active.oldPath ? `${active.oldPath} → ${active.path}` : active.path}
              </span>
              <span className="shrink-0 text-[11px] tabular-nums text-emerald-400">+{active.additions}</span>
              <span className="shrink-0 text-[11px] tabular-nums text-rose-400">−{active.deletions}</span>
              {fileComments.length > 0 && (
                <span
                  className="flex shrink-0 items-center gap-1 rounded-full border border-[#ff7a45]/25 bg-[#ff7a45]/10 px-1.5 py-0.5 text-[10px] font-medium text-[#ff7a45]"
                  title="Line-comments on this file (sent to the agent at its next edit)"
                >
                  <MessageSquarePlus className="size-3" /> {fileComments.length}
                </span>
              )}
              {heldCount > 0 && (
                <button
                  type="button"
                  onClick={() => void patchComment({ release: true })}
                  title="Send the held comments to the agent as one batch (delivered at its next edit)"
                  className="flex shrink-0 items-center gap-1 rounded-full border border-[#ff7a45]/40 bg-[#ff7a45]/15 px-2 py-0.5 text-[10px] font-semibold text-[#ff7a45] transition-colors hover:bg-[#ff7a45]/25"
                >
                  Release {heldCount} held
                </button>
              )}
              <span className="hidden shrink-0 text-[10px] text-muted-foreground/45 lg:inline">
                hover a line · + to comment
              </span>
              <div className="ml-auto flex shrink-0 items-center gap-0.5">
                <div className="flex items-center gap-0.5 rounded-full border border-white/10 p-0.5">
                  <button
                    type="button"
                    onClick={() => setMode("split")}
                    title="Split view"
                    className={cn(
                      "flex size-6 items-center justify-center rounded-full transition-colors",
                      mode === "split" ? "bg-white/10 text-foreground" : "text-muted-foreground hover:text-foreground",
                    )}
                  >
                    <Columns2 className="size-3.5" />
                  </button>
                  <button
                    type="button"
                    onClick={() => setMode("unified")}
                    title="Unified view"
                    className={cn(
                      "flex size-6 items-center justify-center rounded-full transition-colors",
                      mode === "unified" ? "bg-white/10 text-foreground" : "text-muted-foreground hover:text-foreground",
                    )}
                  >
                    <Rows2 className="size-3.5" />
                  </button>
                </div>
                <button
                  type="button"
                  onClick={() => openInEditor(active.path)}
                  title="Open in editor"
                  className="flex size-6 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-white/[0.06] hover:text-foreground"
                >
                  <ExternalLink className="size-3.5" />
                </button>
              </div>
            </div>
            <div className="min-h-0 flex-1 overflow-auto">
              {/* Orphaned comments — the agent changed/removed the commented line. Kept visible
                  (supervision happy path: the agent responded to you), never silently dropped. */}
              {orphans.length > 0 && (
                <div className="border-b border-amber-400/20 bg-amber-400/[0.05] px-3 py-2">
                  <div className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-amber-300/90">
                    The agent changed these lines since your comment
                  </div>
                  {orphans.map((c) => (
                    <CommentCard
                      key={c.id}
                      c={c}
                      orphaned
                      onDelete={() => void deleteComment(c.id)}
                      onToggleHeld={(held) => void patchComment({ id: c.id, held })}
                    />
                  ))}
                </div>
              )}
              {active.binary ? (
                <DiffNote icon>Binary file — no text diff.</DiffNote>
              ) : active.tooLarge ? (
                <DiffNote icon onOpen={() => openInEditor(active.path)}>
                  Diff too large to render here.
                </DiffNote>
              ) : !diffReady ? (
                <DiffNote>Loading diff…</DiffNote>
              ) : !parsed || parsed.hunks.length === 0 ? (
                <DiffNote>No textual changes.</DiffNote>
              ) : (
                <Diff
                  className="beacon-diff"
                  viewType={mode}
                  diffType={parsed.type}
                  hunks={parsed.hunks}
                  tokens={tokens}
                  widgets={widgets}
                  gutterEvents={gutterEvents}
                  renderGutter={renderGutter}
                >
                  {(hunks) =>
                    hunks.map((h) =>
                      hunkIsFormattingOnly(h) && !showFormatting.has(h.content) ? (
                        <Decoration key={h.content}>
                          <div className="flex items-center gap-2 bg-white/[0.02] px-4 py-1 text-[11px] text-muted-foreground">
                            <span>· formatting-only hunk ({h.changes.filter((c) => c.type !== "normal").length} lines)</span>
                            <button
                              type="button"
                              onClick={() => setShowFormatting((s) => new Set([...s, h.content]))}
                              className="rounded-full border border-white/12 px-2 py-0.5 text-[10px] hover:bg-white/[0.06]"
                            >
                              show
                            </button>
                          </div>
                        </Decoration>
                      ) : (
                        <Hunk key={h.content} hunk={h} />
                      ),
                    )
                  }
                </Diff>
              )}
            </div>
          </>
        ) : (
          <div className="flex flex-1 items-center justify-center px-6 text-center text-sm text-muted-foreground">
            {!repo
              ? "Not a git repository."
              : files.length === 0
                ? "No uncommitted changes yet — edits the agent makes show up here live."
                : "Select a file to see its diff."}
          </div>
        )}
      </main>
    </div>
  );
}

// A stored line-comment shown as a widget under its diff line — deletable, hold-toggleable, with
// delivery status. The orphan variant shows the ORIGINAL line the comment anchored to.
function CommentCard({
  c,
  orphaned = false,
  onDelete,
  onToggleHeld,
}: {
  c: DiffComment;
  orphaned?: boolean;
  onDelete: () => void;
  onToggleHeld: (held: boolean) => void;
}) {
  const status = c.deliveredAt
    ? "sent to agent"
    : c.held
      ? "held — release to send"
      : "pending — sent on the agent's next edit";
  return (
    <div className="group mb-1 flex items-start gap-2 rounded-md border border-white/10 bg-background/60 px-2.5 py-1.5">
      <MessageSquarePlus className="mt-0.5 size-3.5 shrink-0 text-[#ff7a45]" />
      <div className="min-w-0 flex-1">
        {orphaned && c.text && (
          <div className="mb-0.5 truncate font-mono text-[10px] text-muted-foreground/70" title={c.text}>
            was: <span className="line-through">{c.text}</span>
          </div>
        )}
        <div className="whitespace-pre-wrap text-[12px] leading-snug text-foreground/90">{c.body}</div>
        <div className="mt-0.5 flex items-center gap-1.5 text-[9px] uppercase tracking-wide text-muted-foreground/60">
          <span>line {c.line} · {status}</span>
          {!c.deliveredAt && (
            <button
              type="button"
              onClick={() => onToggleHeld(!c.held)}
              className={cn(
                "rounded-full border px-1.5 py-px font-semibold transition-colors",
                c.held
                  ? "border-[#ff7a45]/40 text-[#ff7a45] hover:bg-[#ff7a45]/15"
                  : "border-white/15 text-muted-foreground hover:text-foreground",
              )}
              title={c.held ? "Release this comment (sends at the agent's next edit)" : "Hold this comment back to batch it"}
            >
              {c.held ? "release" : "hold"}
            </button>
          )}
        </div>
      </div>
      <button
        type="button"
        onClick={onDelete}
        title="Delete comment"
        className="shrink-0 rounded p-0.5 text-muted-foreground/60 opacity-0 transition-opacity hover:text-red-300 group-hover:opacity-100"
      >
        <Trash2 className="size-3" />
      </button>
    </div>
  );
}

// Inline composer opened from a line's hover-"+" (or a gutter click).
function ComposerBox({
  value,
  onChange,
  hold,
  onHold,
  onSubmit,
  onCancel,
}: {
  value: string;
  onChange: (v: string) => void;
  hold: boolean;
  onHold: (h: boolean) => void;
  onSubmit: () => void;
  onCancel: () => void;
}) {
  return (
    <div className="mt-1">
      <textarea
        autoFocus
        value={value}
        onChange={(e) => onChange(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
            e.preventDefault();
            onSubmit();
          } else if (e.key === "Escape") {
            e.preventDefault();
            onCancel();
          }
        }}
        rows={2}
        placeholder="Comment on this line — the agent gets it at its next edit (⌘/Ctrl+Enter to send)"
        className="w-full resize-y rounded border border-white/10 bg-background px-2 py-1.5 text-[12px] leading-snug outline-none focus:border-[#ff7a45]/40"
      />
      <div className="mt-1 flex items-center gap-2">
        <button
          type="button"
          onClick={onSubmit}
          disabled={!value.trim()}
          className={cn(
            "rounded-md px-2 py-1 text-[11px] font-semibold transition-colors",
            value.trim() ? "bg-[#ff7a45]/20 text-[#ff7a45] hover:bg-[#ff7a45]/30" : "text-muted-foreground opacity-50",
          )}
        >
          Comment
        </button>
        <button
          type="button"
          onClick={onCancel}
          className="rounded-md px-2 py-1 text-[11px] text-muted-foreground transition-colors hover:text-foreground"
        >
          Cancel
        </button>
        <label className="ml-auto flex cursor-pointer items-center gap-1 text-[10px] text-muted-foreground" title="Hold this comment back — batch several, then Release to send them together">
          <input
            type="checkbox"
            checked={hold}
            onChange={(e) => onHold(e.target.checked)}
            className="size-3 accent-[#ff7a45]"
          />
          hold (batch)
        </label>
      </div>
    </div>
  );
}

const TONE: Record<GroupTone, { text: string; icon?: boolean }> = {
  plan: { text: "text-emerald-300/80" },
  warn: { text: "text-amber-300", icon: true },
  muted: { text: "text-muted-foreground" },
};

function TreeGroup({
  label,
  tone,
  files,
  onSelect,
  defaultOpen = true,
  emptyNote,
}: {
  label: string;
  tone: GroupTone;
  files: ChangedFile[];
  onSelect: (path: string) => void;
  defaultOpen?: boolean;
  emptyNote?: string;
}) {
  const [open, setOpen] = useState(defaultOpen);
  const t = TONE[tone];
  return (
    <div className="mb-1">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className={cn("flex w-full items-center gap-1.5 rounded px-2 py-1 text-[10px] font-semibold uppercase tracking-wide transition-colors hover:bg-white/[0.04]", t.text)}
      >
        <ChevronRight className={cn("size-3 shrink-0 transition-transform", open && "rotate-90")} />
        {t.icon && <AlertTriangle className="size-3 shrink-0" />}
        <span className="truncate">{label}</span>
        <span className="ml-auto tabular-nums opacity-70">{files.length}</span>
      </button>
      {open &&
        (files.length > 0 ? (
          <FileTree files={toTree(files)} onSelect={onSelect} />
        ) : emptyNote ? (
          <p className="px-2 py-1 pl-6 text-[10px] text-muted-foreground/70">{emptyNote}</p>
        ) : null)}
    </div>
  );
}

function DiffNote({
  children,
  icon,
  onOpen,
}: {
  children: React.ReactNode;
  icon?: boolean;
  onOpen?: () => void;
}) {
  return (
    <div className="flex items-center gap-2 px-4 py-6 text-[12px] text-muted-foreground">
      {icon && <FileWarning className="size-4 shrink-0 text-amber-300/80" />}
      <span>{children}</span>
      {onOpen && (
        <button
          type="button"
          onClick={onOpen}
          className="rounded-full border border-white/12 px-2 py-0.5 text-[11px] text-foreground transition-colors hover:bg-white/[0.06]"
        >
          Open in editor
        </button>
      )}
    </div>
  );
}
