"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  parseDiff,
  tokenize,
  markEdits,
  Diff,
  Hunk,
  Decoration,
  getChangeKey,
  computeNewLineNumber,
  computeOldLineNumber,
  isDelete,
  type FileData,
  type ChangeData,
  type ChangeEventArgs,
  type HunkData,
  type GutterOptions,
} from "react-diff-view";
import "react-diff-view/style/index.css";
import { refractor } from "refractor";
import { Columns2, Rows2, ExternalLink, FileWarning, Maximize2, MessageSquarePlus, Trash2 } from "lucide-react";
import { currentTabWs } from "@/lib/tab-ws";
import { isWhitespaceOnlyHunk } from "@/lib/diff-shared";
import type { ChangedFile, FileDiff } from "@/lib/diff-shared";
import type { DiffComment } from "@/lib/diff-comments";
import { cn } from "@/lib/utils";

// ONE file's diff, self-contained: lazy raw-diff fetch, Prism highlighting + markEdits word-level
// emphasis, whitespace-only hunk folding, and the full line-comment machinery (hover-+, content
// re-anchoring, orphan strip, hold-to-batch). Used INLINE under an expanded overview card AND as
// the detail page's right pane — mount with key={file.path} so state resets per file.

type ViewType = "split" | "unified";

// react-diff-view's tokenize expects refractor.highlight() to return an ARRAY of hast nodes (its
// v3 API); refractor v5 returns a Root, so unwrap to .children.
const refractorAdapter = {
  highlight: (value: string, lang: string) => refractor.highlight(value, lang).children,
};

// Prism token palette (dark) for the tokenized diff. Injected as a runtime <style> because
// Tailwind/Turbopack strips hand-written `.token.*` rules from globals.css (the classes are
// generated by refractor at runtime, so the build's purge drops them).
const PRISM_CSS = `
.beacon-diff .token.comment,.beacon-diff .token.prolog,.beacon-diff .token.doctype,.beacon-diff .token.cdata{color:#6b7684;font-style:italic}
.beacon-diff .token.punctuation{color:#9aa4b2}
.beacon-diff .token.keyword,.beacon-diff .token.atrule,.beacon-diff .token.important,.beacon-diff .token.rule{color:#c792ea}
.beacon-diff .token.string,.beacon-diff .token.char,.beacon-diff .token.attr-value,.beacon-diff .token.regex{color:#a5d6a7}
.beacon-diff .token.number,.beacon-diff .token.boolean,.beacon-diff .token.constant,.beacon-diff .token.symbol{color:#f78c6c}
.beacon-diff .token.function,.beacon-diff .token.class-name,.beacon-diff .token.maybe-class-name{color:#82aaff}
.beacon-diff .token.tag,.beacon-diff .token.property,.beacon-diff .token.selector,.beacon-diff .token.attr-name,.beacon-diff .token.builtin{color:#ffcb6b}
.beacon-diff .token.operator,.beacon-diff .token.entity,.beacon-diff .token.url{color:#89ddff}
.beacon-diff .token.variable{color:#f07178}
`;

export function openInEditor(path: string) {
  fetch(`/api/open?path=${encodeURIComponent(path)}`).catch(() => {});
}

// A hunk whose every changed line is whitespace-only reflow — folded by default.
function hunkIsFormattingOnly(h: HunkData): boolean {
  const removed = h.changes.filter((c) => c.type === "delete").map((c) => c.content);
  const added = h.changes.filter((c) => c.type === "insert").map((c) => c.content);
  return (removed.length > 0 || added.length > 0) && isWhitespaceOnlyHunk(removed, added);
}

export function FileDiffView({
  file,
  defaultMode = "split",
  onFocus,
  maxBodyHeight,
}: {
  file: ChangedFile;
  defaultMode?: ViewType;
  // Present → a "Focus" button opens this file full-page (the detail view) for concentration.
  onFocus?: () => void;
  // Inline usage caps the body so one expanded card can't swallow the whole overview.
  maxBodyHeight?: number;
}) {
  const [mode, setMode] = useState<ViewType>(defaultMode);

  // Lazy raw diff fetch (re-fetches when the file's counts change → sig in the parent key).
  const [raw, setRaw] = useState<{ path: string; diff: string } | null>(null);
  useEffect(() => {
    if (file.binary || file.tooLarge) return;
    let ignore = false;
    const ws = currentTabWs();
    fetch(`/api/changes?path=${encodeURIComponent(file.path)}&old=${encodeURIComponent(file.oldPath ?? "")}`, {
      cache: "no-store",
      headers: ws ? { "x-beacon-workspace": ws } : undefined,
    })
      .then((r) => r.json() as Promise<FileDiff>)
      .then((c) => {
        if (!ignore) setRaw({ path: file.path, diff: c.diff ?? "" });
      })
      .catch(() => {});
    return () => {
      ignore = true;
    };
  }, [file.path, file.oldPath, file.binary, file.tooLarge, file.additions, file.deletions]);

  const parsed: FileData | null = useMemo(() => {
    if (!raw?.diff) return null;
    try {
      const fs = parseDiff(raw.diff);
      return fs.find((f) => f.newPath === raw.path) ?? fs[0] ?? null;
    } catch {
      return null;
    }
  }, [raw]);

  const tokens = useMemo(() => {
    if (!parsed) return undefined;
    try {
      return tokenize(parsed.hunks, {
        highlight: refractor.registered(file.lang),
        refractor: refractorAdapter,
        language: file.lang,
        enhancers: [markEdits(parsed.hunks, { type: "block" })],
      });
    } catch {
      return undefined;
    }
  }, [parsed, file.lang]);
  const diffReady = raw && raw.path === file.path;

  // Whitespace-only hunks the user explicitly expanded.
  const [showFormatting, setShowFormatting] = useState<Set<string>>(new Set());

  // ── Line-comments (hover-+ → composer; content re-anchoring; hold-to-batch) ──
  const [fileComments, setFileComments] = useState<DiffComment[]>([]);
  const [composer, setComposer] = useState<{ key: string; line: number; side: "old" | "new"; text: string } | null>(null);
  const [draft, setDraft] = useState("");
  const [holdDraft, setHoldDraft] = useState(false);
  const reloadComments = useCallback(async () => {
    const ws = currentTabWs();
    const r = (await fetch(`/api/changes/comment?file=${encodeURIComponent(file.path)}`, {
      cache: "no-store",
      headers: ws ? { "x-beacon-workspace": ws } : undefined,
    })
      .then((res) => res.json())
      .catch(() => null)) as { comments?: DiffComment[] } | null;
    setFileComments(r?.comments ?? []);
  }, [file.path]);
  useEffect(() => {
    // Async subscription to the comment store (state lands in a callback, never synchronously).
    let ignore = false;
    const ws = currentTabWs();
    fetch(`/api/changes/comment?file=${encodeURIComponent(file.path)}`, {
      cache: "no-store",
      headers: ws ? { "x-beacon-workspace": ws } : undefined,
    })
      .then((res) => res.json() as Promise<{ comments?: DiffComment[] }>)
      .then((r) => {
        if (!ignore) setFileComments(r?.comments ?? []);
      })
      .catch(() => {});
    return () => {
      ignore = true;
    };
  }, [file.path]);

  const addComment = useCallback(async () => {
    if (!composer || !draft.trim()) return;
    const ws = currentTabWs();
    await fetch("/api/changes/comment", {
      method: "POST",
      headers: { "content-type": "application/json", ...(ws ? { "x-beacon-workspace": ws } : {}) },
      body: JSON.stringify({
        file: file.path,
        line: composer.line,
        side: composer.side,
        body: draft.trim(),
        text: composer.text,
        held: holdDraft || undefined,
      }),
    }).catch(() => {});
    setComposer(null);
    setDraft("");
    setHoldDraft(false);
    void reloadComments();
  }, [composer, draft, holdDraft, file.path, reloadComments]);

  const patchComment = useCallback(
    async (body: { id?: string; held?: boolean; release?: boolean }) => {
      const ws = currentTabWs();
      await fetch("/api/changes/comment", {
        method: "PATCH",
        headers: { "content-type": "application/json", ...(ws ? { "x-beacon-workspace": ws } : {}) },
        body: JSON.stringify(body),
      }).catch(() => {});
      void reloadComments();
    },
    [reloadComments],
  );

  const deleteComment = useCallback(
    async (id: string) => {
      const ws = currentTabWs();
      await fetch(`/api/changes/comment?id=${encodeURIComponent(id)}`, {
        method: "DELETE",
        headers: ws ? { "x-beacon-workspace": ws } : undefined,
      }).catch(() => {});
      void reloadComments();
    },
    [reloadComments],
  );

  // Index the CURRENT diff two ways: "side:line" → changeKey (composer placement) and
  // side → trimmed content → [{key,line}] (content re-anchoring of stored comments).
  const diffIndex = useMemo(() => {
    const byLine = new Map<string, string>();
    const byContent = {
      old: new Map<string, { key: string; line: number }[]>(),
      new: new Map<string, { key: string; line: number }[]>(),
    };
    if (!parsed) return { byLine, byContent };
    const push = (side: "old" | "new", t: string, key: string, line: number) => {
      if (!t) return;
      const arr = byContent[side].get(t);
      if (arr) arr.push({ key, line });
      else byContent[side].set(t, [{ key, line }]);
    };
    for (const h of parsed.hunks)
      for (const ch of h.changes) {
        const key = getChangeKey(ch);
        const t = ch.content.trim();
        const nl = computeNewLineNumber(ch);
        if (nl && nl > 0) {
          byLine.set(`new:${nl}`, key);
          push("new", t, key, nl);
        }
        const ol = computeOldLineNumber(ch);
        if (ol && ol > 0) {
          byLine.set(`old:${ol}`, key);
          push("old", t, key, ol);
        }
      }
    return { byLine, byContent };
  }, [parsed]);

  const openComposer = useCallback((ch: ChangeData, sideHint?: "old" | "new") => {
    const side: "old" | "new" = sideHint === "old" || (sideHint === undefined && isDelete(ch)) ? "old" : "new";
    const line = side === "old" ? computeOldLineNumber(ch) : computeNewLineNumber(ch);
    if (!line || line <= 0) return;
    setComposer({ key: getChangeKey(ch), line, side, text: ch.content.trim() });
    setDraft("");
  }, []);

  const gutterEvents = useMemo(
    () => ({
      onClick: (args: ChangeEventArgs) => {
        const ch = args.change as ChangeData | null;
        if (ch) openComposer(ch, args.side);
      },
    }),
    [openComposer],
  );

  // Hover a line → ONE "+" affordance (GitHub muscle memory). Each row renders TWO gutter cells
  // (old + new line-number columns), so gate on the side the comment would actually anchor to —
  // old for deletions, new for everything else — or every hover grows a twin pill.
  const renderGutter = useCallback(
    ({ change, side, inHoverState, renderDefault }: GutterOptions) => {
      const anchorSide = change && isDelete(change) ? "old" : "new";
      if (inHoverState && change && side === anchorSide) {
        return (
          <button
            type="button"
            title="Comment on this line — the agent gets it at its next edit"
            className="flex w-full items-center justify-center rounded-sm bg-[#ff7a45] text-[13px] font-bold leading-none text-white"
            onClick={(e) => {
              e.stopPropagation();
              openComposer(change, side);
            }}
          >
            +
          </button>
        );
      }
      return renderDefault();
    },
    [openComposer],
  );

  // Place each stored comment: 1. exact content match on its side (nearest to the stored line),
  // 2. legacy line match, 3. orphaned (the agent changed/removed that line — strip above the diff).
  const { widgets, orphans } = useMemo(() => {
    const byKey = new Map<string, { comments: DiffComment[]; composer: boolean }>();
    const orphaned: DiffComment[] = [];
    const at = (k: string) => {
      let v = byKey.get(k);
      if (!v) {
        v = { comments: [], composer: false };
        byKey.set(k, v);
      }
      return v;
    };
    for (const c of fileComments) {
      const candidates = c.text ? diffIndex.byContent[c.side].get(c.text) : undefined;
      if (candidates?.length) {
        const best = candidates.reduce((a, b) => (Math.abs(a.line - c.line) <= Math.abs(b.line - c.line) ? a : b));
        at(best.key).comments.push(c);
      } else {
        const k = diffIndex.byLine.get(`${c.side}:${c.line}`);
        if (!c.text && k) at(k).comments.push(c);
        else orphaned.push(c);
      }
    }
    if (composer) at(composer.key).composer = true;
    const w: Record<string, React.ReactNode> = {};
    for (const [k, v] of byKey) {
      w[k] = (
        <div className="border-y border-[#ff7a45]/20 bg-[#ff7a45]/[0.04] px-3 py-2">
          {v.comments.map((c) => (
            <CommentCard
              key={c.id}
              c={c}
              onDelete={() => void deleteComment(c.id)}
              onToggleHeld={(held) => void patchComment({ id: c.id, held })}
            />
          ))}
          {v.composer && (
            <ComposerBox
              value={draft}
              onChange={setDraft}
              hold={holdDraft}
              onHold={setHoldDraft}
              onSubmit={() => void addComment()}
              onCancel={() => {
                setComposer(null);
                setDraft("");
              }}
            />
          )}
        </div>
      );
    }
    return { widgets: w, orphans: orphaned };
  }, [fileComments, diffIndex, composer, draft, holdDraft, addComment, deleteComment, patchComment]);

  const heldCount = fileComments.filter((c) => c.held && !c.deliveredAt).length;

  return (
    <div className="flex min-h-0 flex-col">
      <style>{PRISM_CSS}</style>
      {/* Slim toolbar: comment status + release, view mode, focus, open-in-editor. */}
      <div className="flex items-center gap-2 border-b border-white/8 px-3 py-1.5">
        {fileComments.length > 0 && (
          <span
            className="flex shrink-0 items-center gap-1 rounded-full border border-[#ff7a45]/25 bg-[#ff7a45]/10 px-1.5 py-0.5 text-[10px] font-medium text-[#ff7a45]"
            title="Line-comments on this file (sent to the agent at its next edit)"
          >
            <MessageSquarePlus className="size-3" /> {fileComments.length}
          </span>
        )}
        {heldCount > 0 && (
          <button
            type="button"
            onClick={() => void patchComment({ release: true })}
            title="Send the held comments to the agent as one batch (delivered at its next edit)"
            className="flex shrink-0 items-center gap-1 rounded-full border border-[#ff7a45]/40 bg-[#ff7a45]/15 px-2 py-0.5 text-[10px] font-semibold text-[#ff7a45] transition-colors hover:bg-[#ff7a45]/25"
          >
            Release {heldCount} held
          </button>
        )}
        <span className="shrink-0 text-[10px] text-muted-foreground/45">hover a line · + to comment</span>
        <div className="ml-auto flex shrink-0 items-center gap-0.5">
          <div className="flex items-center gap-0.5 rounded-full border border-white/10 p-0.5">
            <button
              type="button"
              onClick={() => setMode("split")}
              title="Split view"
              className={cn(
                "flex size-5 items-center justify-center rounded-full transition-colors",
                mode === "split" ? "bg-white/10 text-foreground" : "text-muted-foreground hover:text-foreground",
              )}
            >
              <Columns2 className="size-3" />
            </button>
            <button
              type="button"
              onClick={() => setMode("unified")}
              title="Unified view"
              className={cn(
                "flex size-5 items-center justify-center rounded-full transition-colors",
                mode === "unified" ? "bg-white/10 text-foreground" : "text-muted-foreground hover:text-foreground",
              )}
            >
              <Rows2 className="size-3" />
            </button>
          </div>
          {onFocus && (
            <button
              type="button"
              onClick={onFocus}
              title="Focus — open this file full-page"
              className="flex size-5 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-white/[0.06] hover:text-foreground"
            >
              <Maximize2 className="size-3" />
            </button>
          )}
          <button
            type="button"
            onClick={() => openInEditor(file.path)}
            title="Open in editor"
            className="flex size-5 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-white/[0.06] hover:text-foreground"
          >
            <ExternalLink className="size-3" />
          </button>
        </div>
      </div>

      <div className="min-h-0 flex-1 overflow-auto" style={maxBodyHeight ? { maxHeight: maxBodyHeight } : undefined}>
        {/* Orphaned comments — the agent changed/removed the commented line. Never dropped. */}
        {orphans.length > 0 && (
          <div className="border-b border-amber-400/20 bg-amber-400/[0.05] px-3 py-2">
            <div className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-amber-300/90">
              The agent changed these lines since your comment
            </div>
            {orphans.map((c) => (
              <CommentCard
                key={c.id}
                c={c}
                orphaned
                onDelete={() => void deleteComment(c.id)}
                onToggleHeld={(held) => void patchComment({ id: c.id, held })}
              />
            ))}
          </div>
        )}
        {file.binary ? (
          <DiffNote icon>Binary file — no text diff.</DiffNote>
        ) : file.tooLarge ? (
          <DiffNote icon onOpen={() => openInEditor(file.path)}>
            Diff too large to render here.
          </DiffNote>
        ) : !diffReady ? (
          <DiffNote>Loading diff…</DiffNote>
        ) : !parsed || parsed.hunks.length === 0 ? (
          <DiffNote>No textual changes.</DiffNote>
        ) : (
          <Diff
            className="beacon-diff"
            viewType={mode}
            diffType={parsed.type}
            hunks={parsed.hunks}
            tokens={tokens}
            widgets={widgets}
            gutterEvents={gutterEvents}
            renderGutter={renderGutter}
          >
            {(hunks) =>
              hunks.map((h) =>
                hunkIsFormattingOnly(h) && !showFormatting.has(h.content) ? (
                  <Decoration key={h.content}>
                    <div className="flex items-center gap-2 bg-white/[0.02] px-4 py-1 text-[11px] text-muted-foreground">
                      <span>· formatting-only hunk ({h.changes.filter((c) => c.type !== "normal").length} lines)</span>
                      <button
                        type="button"
                        onClick={() => setShowFormatting((s) => new Set([...s, h.content]))}
                        className="rounded-full border border-white/12 px-2 py-0.5 text-[10px] hover:bg-white/[0.06]"
                      >
                        show
                      </button>
                    </div>
                  </Decoration>
                ) : (
                  <Hunk key={h.content} hunk={h} />
                ),
              )
            }
          </Diff>
        )}
      </div>
    </div>
  );
}

// A stored line-comment shown as a widget under its diff line — deletable, hold-toggleable, with
// delivery status. The orphan variant shows the ORIGINAL line the comment anchored to.
function CommentCard({
  c,
  orphaned = false,
  onDelete,
  onToggleHeld,
}: {
  c: DiffComment;
  orphaned?: boolean;
  onDelete: () => void;
  onToggleHeld: (held: boolean) => void;
}) {
  const status = c.deliveredAt
    ? "sent to agent"
    : c.held
      ? "held — release to send"
      : "pending — sent on the agent's next edit";
  return (
    <div className="group mb-1 flex items-start gap-2 rounded-md border border-white/10 bg-background/60 px-2.5 py-1.5">
      <MessageSquarePlus className="mt-0.5 size-3.5 shrink-0 text-[#ff7a45]" />
      <div className="min-w-0 flex-1">
        {orphaned && c.text && (
          <div className="mb-0.5 truncate font-mono text-[10px] text-muted-foreground/70" title={c.text}>
            was: <span className="line-through">{c.text}</span>
          </div>
        )}
        <div className="whitespace-pre-wrap text-[12px] leading-snug text-foreground/90">{c.body}</div>
        <div className="mt-0.5 flex items-center gap-1.5 text-[9px] uppercase tracking-wide text-muted-foreground/60">
          <span>
            line {c.line} · {status}
          </span>
          {!c.deliveredAt && (
            <button
              type="button"
              onClick={() => onToggleHeld(!c.held)}
              className={cn(
                "rounded-full border px-1.5 py-px font-semibold transition-colors",
                c.held
                  ? "border-[#ff7a45]/40 text-[#ff7a45] hover:bg-[#ff7a45]/15"
                  : "border-white/15 text-muted-foreground hover:text-foreground",
              )}
              title={c.held ? "Release this comment (sends at the agent's next edit)" : "Hold this comment back to batch it"}
            >
              {c.held ? "release" : "hold"}
            </button>
          )}
        </div>
      </div>
      <button
        type="button"
        onClick={onDelete}
        title="Delete comment"
        className="shrink-0 rounded p-0.5 text-muted-foreground/60 opacity-0 transition-opacity hover:text-red-300 group-hover:opacity-100"
      >
        <Trash2 className="size-3" />
      </button>
    </div>
  );
}

// Inline composer opened from a line's hover-"+" (or a gutter click).
function ComposerBox({
  value,
  onChange,
  hold,
  onHold,
  onSubmit,
  onCancel,
}: {
  value: string;
  onChange: (v: string) => void;
  hold: boolean;
  onHold: (h: boolean) => void;
  onSubmit: () => void;
  onCancel: () => void;
}) {
  return (
    <div className="mt-1">
      <textarea
        autoFocus
        value={value}
        onChange={(e) => onChange(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
            e.preventDefault();
            onSubmit();
          } else if (e.key === "Escape") {
            e.preventDefault();
            onCancel();
          }
        }}
        rows={2}
        placeholder="Comment on this line — the agent gets it at its next edit (⌘/Ctrl+Enter to send)"
        className="w-full resize-y rounded border border-white/10 bg-background px-2 py-1.5 text-[12px] leading-snug outline-none focus:border-[#ff7a45]/40"
      />
      <div className="mt-1 flex items-center gap-2">
        <button
          type="button"
          onClick={onSubmit}
          disabled={!value.trim()}
          className={cn(
            "rounded-md px-2 py-1 text-[11px] font-semibold transition-colors",
            value.trim() ? "bg-[#ff7a45]/20 text-[#ff7a45] hover:bg-[#ff7a45]/30" : "text-muted-foreground opacity-50",
          )}
        >
          Comment
        </button>
        <button
          type="button"
          onClick={onCancel}
          className="rounded-md px-2 py-1 text-[11px] text-muted-foreground transition-colors hover:text-foreground"
        >
          Cancel
        </button>
        <label
          className="ml-auto flex cursor-pointer items-center gap-1 text-[10px] text-muted-foreground"
          title="Hold this comment back — batch several, then Release to send them together"
        >
          <input type="checkbox" checked={hold} onChange={(e) => onHold(e.target.checked)} className="size-3 accent-[#ff7a45]" />
          hold (batch)
        </label>
      </div>
    </div>
  );
}

function DiffNote({ children, icon, onOpen }: { children: React.ReactNode; icon?: boolean; onOpen?: () => void }) {
  return (
    <div className="flex items-center gap-2 px-4 py-6 text-[12px] text-muted-foreground">
      {icon && <FileWarning className="size-4 shrink-0 text-amber-300/80" />}
      <span>{children}</span>
      {onOpen && (
        <button
          type="button"
          onClick={onOpen}
          className="rounded-full border border-white/12 px-2 py-0.5 text-[11px] text-foreground transition-colors hover:bg-white/[0.06]"
        >
          Open in editor
        </button>
      )}
    </div>
  );
}
