import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "bun:test";
import { upsertBlock } from "@/lib/context-files";

// Regression: a convention line QUOTING the literal markers ("the block lives between
// <!-- beacon:start --> and <!-- beacon:end -->") made the non-greedy marker replace cut
// at the EMBEDDED end-marker and leak the block's tail below the section — one more copy
// per regeneration (AGENTS.md reached 1034 duplicated fragments).

const START = "<!-- beacon:start -->";
const END = "<!-- beacon:end -->";
const dir = () => mkdtempSync(join(tmpdir(), "beacon-context-block-"));

const QUOTING_BLOCK = [
  "## Project",
  `- The AGENTS.md project block lives between ${START} and ${END} and is regenerated.`,
  "- TDD on non-trivial changes.",
].join("\n");

describe("upsertBlock", () => {
  it("is idempotent even when the block body quotes the marker strings", () => {
    const file = join(dir(), "AGENTS.md");
    upsertBlock(file, QUOTING_BLOCK, "# AGENTS.md");
    const once = readFileSync(file, "utf8");
    upsertBlock(file, QUOTING_BLOCK, "# AGENTS.md");
    upsertBlock(file, QUOTING_BLOCK, "# AGENTS.md");
    expect(readFileSync(file, "utf8")).toBe(once);
    // Exactly one real start and one real end marker survive.
    expect(once.split(START).length - 1).toBe(1);
    expect(once.split(END).length - 1).toBe(1);
  });

  it("heals a file that already accumulated duplicated block fragments", () => {
    const file = join(dir(), "AGENTS.md");
    const junkTail = ` and is regenerated by lib/context-files.ts — edit outside the markers.\n\n_Maintained by Beacon._\n`;
    writeFileSync(
      file,
      `# Header\n\n${START}\nold body quoting ${END}${junkTail}${junkTail}${START}\nstray\n${END}\n\n## Hand-written section below\n`,
    );
    upsertBlock(file, "clean body", "# AGENTS.md");
    const healed = readFileSync(file, "utf8");
    expect(healed.split(START).length - 1).toBe(1);
    expect(healed.split(END).length - 1).toBe(1);
    expect(healed).toContain("clean body");
    expect(healed).toContain("# Header");
    expect(healed).toContain("## Hand-written section below");
    expect(healed).not.toContain("stray");
  });

  it("appends a single block to an unmanaged file", () => {
    const file = join(dir(), "AGENTS.md");
    writeFileSync(file, "# Existing notes\n");
    upsertBlock(file, "body", "# AGENTS.md");
    const out = readFileSync(file, "utf8");
    expect(out).toContain("# Existing notes");
    expect(out.split(START).length - 1).toBe(1);
  });
});
