import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { beaconHome } from "@/lib/workspaces";
import { readPreferences, writePreferences } from "@/lib/preferences";
import { writeJsonAtomic } from "@/lib/atomic-write";
import { SITE_URL } from "@/lib/release";

// Anonymous usage telemetry — counts UNIQUE ACTIVE MACHINES, which npm download numbers
// can't (they're raw tarball GETs, dominated by mirrors/CI/scanners). The full contract:
//
//   • Identity: ONE random UUID per machine, generated by the CLI (never the daemon) and
//     persisted in ~/.beacon/preferences.json. Its absence doubles as the "first ever run"
//     signal for the one-time disclosure notice in `beacon`.
//   • Payload: exactly { machineId, version, platform, arch, ci }. Never repo names,
//     paths, code, or anything derived from them — heartbeatPayload is the single place
//     the payload is built, and tests pin its exact key set.
//   • Cadence: the daemon heartbeats on boot and then at most every 12h (gate persisted in
//     ~/.beacon/telemetry.json, written atomically — the daemon NEVER writes preferences,
//     so a concurrent `beacon telemetry off` can't be lost to a read-modify-write race).
//   • Opt-outs: `beacon telemetry off` (preference), BEACON_TELEMETRY_DISABLED=1, and the
//     cross-tool DO_NOT_TRACK convention. BEACON_TELEMETRY_DEBUG=1 prints instead of sending.
//   • Failure mode: fire-and-forget — short timeout, blanket catch; telemetry must never
//     block or break a boot, and a failed send simply retries on the next hourly tick.

const HEARTBEAT_INTERVAL_MS = 12 * 60 * 60 * 1000; // at most one heartbeat per 12h
const CHECK_INTERVAL_MS = 60 * 60 * 1000; // hourly gate checks survive laptop sleep

export interface HeartbeatPayload {
  machineId: string;
  version: string;
  platform: string;
  arch: string;
  ci: boolean;
}

interface HeartbeatState {
  lastHeartbeatAt?: string;
}

type Env = Record<string, string | undefined>;

/** Generate-once machine id. CLI-side only — the daemon reads, never writes, preferences. */
export function ensureTelemetryId(): string {
  const existing = readPreferences().telemetryUuid;
  if (existing) return existing;
  const id = randomUUID();
  writePreferences({ telemetryUuid: id });
  return id;
}

/** Effective on/off: env opt-outs win over the stored preference; default is ON. */
export function isTelemetryEnabled(env: Env = process.env): boolean {
  if (env.BEACON_TELEMETRY_DISABLED === "1") return false;
  const dnt = env.DO_NOT_TRACK;
  if (dnt !== undefined && dnt !== "" && dnt !== "0" && dnt !== "false") return false;
  return readPreferences().telemetryEnabled !== false;
}

/** `beacon telemetry on|off`. Also ensures the machine id exists — explicitly toggling means
 *  the user has seen telemetry, so the first-run notice (gated on a missing id) won't repeat. */
export function setTelemetryEnabled(enabled: boolean): void {
  ensureTelemetryId();
  writePreferences({ telemetryEnabled: enabled });
}

/** Effective state + WHY, for `beacon telemetry status`. */
export function telemetryStatus(env: Env = process.env): {
  enabled: boolean;
  reason: "env:BEACON_TELEMETRY_DISABLED" | "env:DO_NOT_TRACK" | "preference" | "default";
  machineId: string | null;
} {
  const machineId = readPreferences().telemetryUuid ?? null;
  if (env.BEACON_TELEMETRY_DISABLED === "1")
    return { enabled: false, reason: "env:BEACON_TELEMETRY_DISABLED", machineId };
  const dnt = env.DO_NOT_TRACK;
  if (dnt !== undefined && dnt !== "" && dnt !== "0" && dnt !== "false")
    return { enabled: false, reason: "env:DO_NOT_TRACK", machineId };
  if (readPreferences().telemetryEnabled === false)
    return { enabled: false, reason: "preference", machineId };
  return { enabled: true, reason: "default", machineId };
}

function statePath(): string {
  return join(beaconHome(), "telemetry.json");
}

export function readHeartbeatState(): HeartbeatState {
  try {
    const raw = JSON.parse(readFileSync(statePath(), "utf8")) as HeartbeatState;
    return { lastHeartbeatAt: typeof raw.lastHeartbeatAt === "string" ? raw.lastHeartbeatAt : undefined };
  } catch {
    return {};
  }
}

export function writeHeartbeatState(state: HeartbeatState): void {
  writeJsonAtomic(statePath(), state);
}

/** Pure 12h gate: garbage/absent timestamps mean "fire now". */
export function shouldHeartbeat(lastHeartbeatAt: string | undefined, now: Date): boolean {
  if (!lastHeartbeatAt) return true;
  const last = Date.parse(lastHeartbeatAt);
  if (Number.isNaN(last)) return true;
  return now.getTime() - last >= HEARTBEAT_INTERVAL_MS;
}

/** The complete payload — these five fields and NOTHING else (privacy contract). */
export function heartbeatPayload(version: string, env: Env = process.env): HeartbeatPayload {
  return {
    machineId: readPreferences().telemetryUuid ?? "",
    version,
    platform: process.platform,
    arch: process.arch,
    ci: Boolean(env.CI && env.CI !== "false"),
  };
}

/** One fire-and-forget heartbeat. Resolves silently on every failure path. */
export async function sendHeartbeat(
  version: string,
  opts: { env?: Env; fetchImpl?: typeof fetch; now?: Date } = {},
): Promise<void> {
  const env = opts.env ?? process.env;
  try {
    if (!isTelemetryEnabled(env)) return;
    const payload = heartbeatPayload(version, env);
    if (env.BEACON_TELEMETRY_DEBUG === "1") {
      console.log(`[beacon-telemetry] debug — would send: ${JSON.stringify(payload)}`);
      return;
    }
    if (!payload.machineId) return; // uuid is the CLI's job — never invent one here
    const doFetch = opts.fetchImpl ?? fetch;
    const res = await doFetch(`${SITE_URL}/api/telemetry`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(3000),
    });
    // Record the gate only on success so an offline boot retries on the next hourly tick.
    if (res.ok) writeHeartbeatState({ lastHeartbeatAt: (opts.now ?? new Date()).toISOString() });
  } catch {
    /* telemetry must never throw */
  }
}

/** Daemon entrypoint: boot ping + hourly gate checks. Deduped across HMR reboots. */
export function startTelemetry(version: string): void {
  const g = globalThis as unknown as { __beaconTelemetry?: boolean };
  if (g.__beaconTelemetry) return;
  g.__beaconTelemetry = true;

  const maybeHeartbeat = () => {
    try {
      if (!shouldHeartbeat(readHeartbeatState().lastHeartbeatAt, new Date())) return;
      void sendHeartbeat(version);
    } catch {
      /* never break the host process */
    }
  };
  maybeHeartbeat();
  setInterval(maybeHeartbeat, CHECK_INTERVAL_MS).unref();
}
